// import { ApiCarResponse } from '../app/interfaces/car-data-interface';

export const CAR_MOCK: any = {
  response: [
    {
      id: 'A1',
      aceitaTroca: 'Sim',
      unicoDono: 'Não',
      cor: 'Prata',
      ipvaPago: 'Não',
      finalPlaca: 1,
      marca: 'Volkswagen',
      ano: 2017,
      modelo: 'Gol',
      combustivel: 'Gasolina',
      preco: 58000,
      quilometragem: 80000,
      cambio: 'Manual',
      imagens: [
        {
          id: 'cliente1/xV7jqo1eDfTjR8KXQMV3/Volkswagen_Gol_Gasolina',
          url: 'https://s3.carro57.com.br/FC/11247/6225822_0_W_d810291724.jpg',
        },
        {
          id: 'cliente1/xV7jqo1eDfTjR8KXQMV3/Volkswagen_Gol_Gasolina',
          url: 'https://mkt.carrera.com.br/stock-images/115669-01-548079.jpg?withwebp',
        },
      ],
    },
    {
      id: 'A2',
      aceitaTroca: 'Não',
      unicoDono: 'Sim',
      cor: 'Vermelho',
      ipvaPago: 'Sim',
      finalPlaca: 8,
      marca: 'Chevrolet',
      ano: 2020,
      modelo: 'Onix',
      combustivel: 'Flex',
      preco: 70000,
      quilometragem: 25000,
      cambio: 'Automático',
      imagens: [
        {
          id: 'cliente1/xV7jqo1eDfTjR8KXQMV3/Chevrolet_Onix_Flex',
          url: 'https://res.cloudinary.com/dixtmxvwe/image/upload/v1731787920/cliente1/xV7jqo1eDfTjR8KXQMV3/Volkswagen_Gol_Gasolina.png',
        },
        {
          id: 'cliente1/xV7jqo1eDfTjR8KXQMV3/Chevrolet_Onix_Flex',
          url: 'https://res.cloudinary.com/dixtmxvwe/image/upload/v1731787920/cliente1/xV7jqo1eDfTjR8KXQMV3/Volkswagen_Gol_Gasolina.png',
        },
      ],
    },
    {
      id: 'A3',
      aceitaTroca: 'Sim',
      unicoDono: 'Não',
      cor: 'Preto',
      ipvaPago: 'Sim',
      finalPlaca: 5,
      marca: 'Toyota',
      ano: 2018,
      modelo: 'Corolla',
      combustivel: 'Híbrido',
      preco: 90000,
      quilometragem: 60000,
      cambio: 'Automático',
      imagens: [
        {
          id: 'cliente1/xV7jqo1eDfTjR8KXQMV3/Toyota_Corolla_Hibrido',
          url: 'https://res.cloudinary.com/dixtmxvwe/image/upload/v1731787920/cliente1/xV7jqo1eDfTjR8KXQMV3/Volkswagen_Gol_Gasolina.png',
        },
        {
          id: 'cliente1/xV7jqo1eDfTjR8KXQMV3/Toyota_Corolla_Hibrido',
          url: 'https://res.cloudinary.com/dixtmxvwe/image/upload/v1731787920/cliente1/xV7jqo1eDfTjR8KXQMV3/Volkswagen_Gol_Gasolina.png',
        },
      ],
    },
    {
      id: 'A4',
      aceitaTroca: 'Não',
      unicoDono: 'Sim',
      cor: 'Azul',
      ipvaPago: 'Não',
      finalPlaca: 2,
      marca: 'Ford',
      ano: 2019,
      modelo: 'Fiesta',
      combustivel: 'Gasolina',
      preco: 65000,
      quilometragem: 40000,
      cambio: 'Manual',
      imagens: [
        {
          id: 'cliente1/xV7jqo1eDfTjR8KXQMV3/Ford_Fiesta_Gasolina',
          url: 'https://res.cloudinary.com/dixtmxvwe/image/upload/v1731787920/cliente1/xV7jqo1eDfTjR8KXQMV3/Volkswagen_Gol_Gasolina.png',
        },
        {
          id: 'cliente1/xV7jqo1eDfTjR8KXQMV3/Ford_Fiesta_Gasolina',
          url: 'https://res.cloudinary.com/dixtmxvwe/image/upload/v1731787920/cliente1/xV7jqo1eDfTjR8KXQMV3/Volkswagen_Gol_Gasolina.png',
        },
      ],
    },
    {
      id: 'A5',
      aceitaTroca: 'Sim',
      unicoDono: 'Não',
      cor: 'Branco',
      ipvaPago: 'Sim',
      finalPlaca: 9,
      marca: 'Hyundai',
      ano: 2021,
      modelo: 'HB20',
      combustivel: 'Flex',
      preco: 80000,
      quilometragem: 20000,
      cambio: 'Automático',
      imagens: [
        {
          id: 'cliente1/xV7jqo1eDfTjR8KXQMV3/Hyundai_HB20_Flex',
          url: 'https://res.cloudinary.com/dixtmxvwe/image/upload/v1731787920/cliente1/xV7jqo1eDfTjR8KXQMV3/Volkswagen_Gol_Gasolina.png',
        },
        {
          id: 'cliente1/xV7jqo1eDfTjR8KXQMV3/Hyundai_HB20_Flex',
          url: 'https://res.cloudinary.com/dixtmxvwe/image/upload/v1731787920/cliente1/xV7jqo1eDfTjR8KXQMV3/Volkswagen_Gol_Gasolina.png',
        },
      ],
    },
    {
      id: 'A6',
      aceitaTroca: 'Não',
      unicoDono: 'Sim',
      cor: 'Cinza',
      ipvaPago: 'Sim',
      finalPlaca: 3,
      marca: 'Nissan',
      ano: 2016,
      modelo: 'Sentra',
      combustivel: 'Gasolina',
      preco: 72000,
      quilometragem: 90000,
      cambio: 'Automático',
      imagens: [
        {
          id: 'cliente1/xV7jqo1eDfTjR8KXQMV3/Nissan_Sentra_Gasolina',
          url: 'https://res.cloudinary.com/dixtmxvwe/image/upload/v1731787920/cliente1/xV7jqo1eDfTjR8KXQMV3/Volkswagen_Gol_Gasolina.png',
        },
        {
          id: 'cliente1/xV7jqo1eDfTjR8KXQMV3/Nissan_Sentra_Gasolina',
          url: 'https://res.cloudinary.com/dixtmxvwe/image/upload/v1731787920/cliente1/xV7jqo1eDfTjR8KXQMV3/Volkswagen_Gol_Gasolina.png',
        },
      ],
    },
    {
      id: 'A7',
      aceitaTroca: 'Sim',
      unicoDono: 'Não',
      cor: 'Amarelo',
      ipvaPago: 'Não',
      finalPlaca: 6,
      marca: 'Fiat',
      ano: 2022,
      modelo: 'Punto',
      combustivel: 'Flex',
      preco: 68000,
      quilometragem: 15000,
      cambio: 'Manual',
      imagens: [
        {
          id: 'cliente1/xV7jqo1eDfTjR8KXQMV3/Fiat_Punto_Flex',
          url: 'https://res.cloudinary.com/dixtmxvwe/image/upload/v1731787920/cliente1/xV7jqo1eDfTjR8KXQMV3/Volkswagen_Gol_Gasolina.png',
        },
        {
          id: 'cliente1/xV7jqo1eDfTjR8KXQMV3/Fiat_Punto_Flex',
          url: 'https://res.cloudinary.com/dixtmxvwe/image/upload/v1731787920/cliente1/xV7jqo1eDfTjR8KXQMV3/Volkswagen_Gol_Gasolina.png',
        },
      ],
    },
    {
      id: 'A8',
      aceitaTroca: 'Não',
      unicoDono: 'Sim',
      cor: 'Verde',
      ipvaPago: 'Sim',
      finalPlaca: 7,
      marca: 'Renault',
      ano: 2021,
      modelo: 'Kwid',
      combustivel: 'Elétrico',
      preco: 85000,
      quilometragem: 10000,
      cambio: 'Automático',
      imagens: [
        {
          id: 'cliente1/xV7jqo1eDfTjR8KXQMV3/Renault_Kwid_Eletrico',
          url: 'https://res.cloudinary.com/dixtmxvwe/image/upload/v1731787920/cliente1/xV7jqo1eDfTjR8KXQMV3/Volkswagen_Gol_Gasolina.png',
        },
        {
          id: 'cliente1/xV7jqo1eDfTjR8KXQMV3/Renault_Kwid_Eletrico',
          url: 'https://res.cloudinary.com/dixtmxvwe/image/upload/v1731787920/cliente1/xV7jqo1eDfTjR8KXQMV3/Volkswagen_Gol_Gasolina.png',
        },
      ],
    },
    {
      id: 'A9',
      aceitaTroca: 'Sim',
      unicoDono: 'Não',
      cor: 'Laranja',
      ipvaPago: 'Não',
      finalPlaca: 4,
      marca: 'Honda',
      ano: 2015,
      modelo: 'Civic',
      combustivel: 'Gasolina',
      preco: 74000,
      quilometragem: 95000,
      cambio: 'Manual',
      imagens: [
        {
          id: 'cliente1/xV7jqo1eDfTjR8KXQMV3/Honda_Civic_Gasolina',
          url: 'https://res.cloudinary.com/dixtmxvwe/image/upload/v1731787920/cliente1/xV7jqo1eDfTjR8KXQMV3/Volkswagen_Gol_Gasolina.png',
        },
        {
          id: 'cliente1/xV7jqo1eDfTjR8KXQMV3/Honda_Civic_Gasolina',
          url: 'https://res.cloudinary.com/dixtmxvwe/image/upload/v1731787920/cliente1/xV7jqo1eDfTjR8KXQMV3/Volkswagen_Gol_Gasolina.png',
        },
      ],
    },
    {
      id: 'A10',
      aceitaTroca: 'Não',
      unicoDono: 'Sim',
      cor: 'Roxo',
      ipvaPago: 'Sim',
      finalPlaca: 0,
      marca: 'Peugeot',
      ano: 2023,
      modelo: '208',
      combustivel: 'Flex',
      preco: 92000,
      quilometragem: 5000,
      cambio: 'Automático',
      imagens: [
        {
          id: 'cliente1/xV7jqo1eDfTjR8KXQMV3/Peugeot_208_Flex',
          url: 'https://res.cloudinary.com/dixtmxvwe/image/upload/v1731787920/cliente1/xV7jqo1eDfTjR8KXQMV3/Volkswagen_Gol_Gasolina.png',
        },
        {
          id: 'cliente1/xV7jqo1eDfTjR8KXQMV3/Peugeot_208_Flex',
          url: 'https://res.cloudinary.com/dixtmxvwe/image/upload/v1731787920/cliente1/xV7jqo1eDfTjR8KXQMV3/Volkswagen_Gol_Gasolina.png',
        },
      ],
    },
  ],
};
